### ISSUE TITLE
Nextcloud App Store Download

### ISSUE THREAD

**Issue by stullekovski** [raimund-schluessler/inventory#454]
Hi there,

thanks for your work, looks promising.
Do you plan to make it available at the Nextcloud App-Store, by any chance?
Would be great.

Thanks!

**Comment by raimund-schluessler** [comment]
In principle yes. But there are a few things that I wanted to improve before putting it in the appstore. Otherwise it might be tricky to figure out how the app is intended to be used.

- The documentation is basically missing completely
- There is also no feature list
- Adding items currently only works by comma-separated-values (I import them from an excel file)
- I would like to publish the app using the latest dependencies, which means including vue3, but there is no vue 3 compatible release of `nextcloud/vue` yet, see https://github.com/nextcloud-libraries/nextcloud-vue/milestone/132

The last issue might be done in a couple of weeks, so maybe that will be the time to release it to the appstore.

**Comment by raimund-schluessler** [comment]
The app is now available in the app store.

**Comment by stullekovski** [comment]
Wow! Thanks so much. Will have a look.
Does it work on NC 27 as well?

**Comment by raimund-schluessler** [comment]
> Does it work on NC 27 as well?

In principle yes. But there might be some (minor) styling issues. That's why I set it to Nextcloud 28 and above.
